Expanding Core Schema for FRB
tachgsfc/tach-avro-schema pull request #226
Opened 2024-12-04 05:12 UTC by Vidushi-GitHub

# Description
Observables relevant for radio transients are added.

- Dispersion Measure related
- Sampling Frequency

2024-12-13 03:00 UTC, Vidushi-GitHub commented on gcn/notices/core/DispersionMeasure.schema.json
> +      "description": "Estimated contribution to the dispersion measure [pc/cm^3], from the Galaxy using the NE2001 model ."
```suggestion
      "description": "Estimated contribution to the dispersion measure [pc/cm^3], from the Galaxy using the NE2001 model."
```

2024-12-13 03:07 UTC, Vidushi-GitHub commented on gcn/notices/core/DateTime.schema.json
> +      "description": "Time resolution used for the source search, specified in milliseconds [ms]."
```suggestion
      "description": "Time resolution used for the source search [ms]."
```

2025-01-23 16:39 UTC, jracusin commented on gcn/notices/core/DispersionMeasure.schema.json
> +      "description": "Estimated contribution to the dispersion measure [pc/cm^3], from the Galaxy using the NE2001 model."
```suggestion
      "description": "Estimated contribution to the dispersion measure [pc/cm^3] from the Galaxy using the NE2001 model."
```

2025-01-23 16:41 UTC, jracusin commented on gcn/notices/core/Reporter.schema.json
>      "units": {
We should specify what these units are for.  When flattened, it'll just be units and we should disambiguate.

2025-01-23 16:42 UTC, jracusin commented on package-lock.json
This should not be included in the PR.

2025-02-11 17:47 UTC, tabbott36 requested changes
This looks good to me, my only suggestion is to exclude the "dm_gal_ne_2001_max" from the core schema, as this value is an optional post detection analysis, and the specific model (i.e. NE_2001) may change or become obsolete.

2025-02-12 00:27 UTC, Vidushi-GitHub commented
> The changes I recommend are as follows:
> 
> * I would exclude the "dm_gal_ne_2001_max" from the core schema, as this value is an optional post detection analysis, and the specific model (i.e. NE_2001) may change or become obsolete.
> * In the definition of spectral center, it is written that: "enum": ["energy", "wavelength", "frequency"] and "type": "number" which appears to be contradictory. I suggest removing the "enum": ["energy", "wavelength", "frequency"].
> 
> Note: I've made these changes to [PR #217](https://github.com/nasa-gcn/gcn-schema/pull/217) so that my commits could pass the new consistency checks that this change introduces. I believe this PR can be moved/combined with [PR #217](https://github.com/nasa-gcn/gcn-schema/pull/217).

Thank you, indeed helpful.

2025-02-12 00:27 UTC, Vidushi-GitHub commented on gcn/notices/core/Reporter.schema.json
> +      "description": "Mode of spectral measurement: high-energy or optical or radio observations, if not parsed, then default spectrum is energy",
```suggestion
      "description": "Mode of spectral measurement: high-energy or optical or radio observations, if not parsed, then default is energy",
```

2025-02-12 00:29 UTC, Vidushi-GitHub commented
@jracusin please review it.

2025-02-12 23:28 UTC, Vidushi-GitHub commented
> > The changes I recommend are as follows:
> > 
> > * I would exclude the "dm_gal_ne_2001_max" from the core schema, as this value is an optional post detection analysis, and the specific model (i.e. NE_2001) may change or become obsolete.
> > * In the definition of spectral center, it is written that: "enum": ["energy", "wavelength", "frequency"] and "type": "number" which appears to be contradictory. I suggest removing the "enum": ["energy", "wavelength", "frequency"].
> > 
> > Note: I've made these changes to [PR #217](https://github.com/nasa-gcn/gcn-schema/pull/217) so that my commits could pass the new consistency checks that this change introduces. I believe this PR can be moved/combined with [PR #217](https://github.com/nasa-gcn/gcn-schema/pull/217).
> 
> Thank you, indeed helpful.

@tabbott36 please provide feedback/approve it.

2025-02-19 20:45 UTC, tabbott36 approved these changes
Looks good to me!

2025-02-25 18:45 UTC, jracusin commented on gcn/notices/core/Reporter.schema.json
> +      "description": "Mode of spectral measurement: high-energy or optical or radio observations, if not parsed, then default is energy",
Perhaps this should just be simplified into:
"Mode of spectral measurement; default is energy"

2025-02-25 18:46 UTC, jracusin commented on gcn/notices/core/Reporter.schema.json
> +      "description": "Units for the spectral data, if not parsed, then default unit is keV",
Do we need "if not parsed"?

2025-02-25 20:38 UTC, Vidushi-GitHub commented on gcn/notices/core/Reporter.schema.json
> +      "description": "Mode of spectral measurement: high-energy or optical or radio observations, if not parsed, then default is energy",
```suggestion
      "description": "Mode of spectral measurement; default is energy",
```

2025-02-25 20:39 UTC, Vidushi-GitHub commented on gcn/notices/core/Reporter.schema.json
> +      "description": "Units for the spectral data, if not parsed, then default unit is keV",
```suggestion
      "description": "Units for the spectral data, default unit is keV",
```

2025-02-25 20:40 UTC, Vidushi-GitHub commented on gcn/notices/core/Reporter.schema.json
> +      "description": "Units for the spectral data, default unit is keV",
```suggestion
      "description": "Units for the spectral data; default unit is keV",
```

2025-02-25 20:40 UTC, Vidushi-GitHub commented on gcn/notices/core/Reporter.schema.json
> +      "description": "Units for the spectral data, default unit is keV",
```suggestion
      "description": "Units for the spectral data; default unit is keV",
```

2025-02-27 22:51 UTC, lpsinger requested changes

2025-02-27 22:51 UTC, lpsinger commented on gcn/notices/core/DateTime.schema.json
> +      "description": "Time resolution used for the source search [ms]"
How is this different from `trigger_time_error`?

2025-02-27 22:51 UTC, lpsinger commented on gcn/notices/core/DispersionMeasure.schema.json
> +      "description": "Uncertainity associated with the dispersion measure [pc/cm^3, 1-sigma], with optional asymmetric uncertainty."
If the asymmetric uncertainty is optional, can you please accept either an array or a number?

2025-02-27 23:23 UTC, Vidushi-GitHub commented on gcn/notices/core/DateTime.schema.json
> +      "description": "Time resolution used for the source search [ms]"
time_error is based on instrument time resolution.

time_resolution is choice based on transient type.

2025-02-28 01:12 UTC, lpsinger commented on gcn/notices/core/DateTime.schema.json
> +      "description": "Time resolution used for the source search [ms]"
Discretization is nothing more than a particular source of error. Why do we need a separate field for it?

2025-02-28 19:02 UTC, Vidushi-GitHub commented on gcn/notices/core/DateTime.schema.json
> +      "description": "Time resolution used for the source search [ms]"
It's not instrument property, it's search time scale.
See: https://github.com/nasa-gcn/gcn-schema/pull/217/files

But @jracusin and I agree with removing time_resolution.

2025-02-28 19:07 UTC, jracusin commented on gcn/notices/core/DispersionMeasure.schema.json
> +      "description": "Uncertainity associated with the dispersion measure [pc/cm^3, 1-sigma], with optional asymmetric uncertainty."
Are you asking for it to be like `ra_dec_error` where you can give it either a number or an array?  The way this is written now, it can be "[1.0]" or "[-1.0,+1.0]".  If we want to do like `ra_dec_error`, there are a bunch of other core schema that will need to be redefined.

2025-03-03 18:24 UTC, merged